### ISSUE TITLE
edit 화면의  textarea 의 기본 폰트 크기를 preview쪽 기본 폰트크기와 일치시켜주세요.

### ISSUE THREAD

**Issue by silsol** [Aha00a/AhaWiki#17]
편집화면과 미리보기 화면의 동기화를 100%할수야 없겠지만 기본폰트 크기가 동일하면 어느정도 비슷해지지 않을까 싶습니다.

**Comment by Aha00a** [comment]
You can add custom css in `.header` page.
The css selector of textarea is `.AhaWiki .wikiContent .edit textarea[name=text]`.

for example
```html
<style type="text/css">
    .AhaWiki .wikiContent .edit textarea[name=text] {
        font-size: 16px;
    }
</style>
```
I added that snippets into your wiki site.
Thanks.
