### ISSUE TITLE
Cannot include a page that its name has any blanks

### ISSUE THREAD

**Issue by jinwoo-nativebinary** [Aha00a/AhaWiki#18]
For example,
```
[[Include(upgrade Jenkins)]]
```
or
```
[[Include(upgrade%20Jenkins)]]
```
are cannot include the pages.

**Comment by jinwoo-nativebinary** [comment]
Sorry. My mistake.
`[[Include(upgrade Jenkins)]]` works.

**Comment by Aha00a** [comment]
AhaWiki doesn't support whitespace character for PageName by design.
I think it's a matter of taste.
I also modified that wiki page.
Thanks for your interests.
