### ISSUE TITLE
SimilarPages error

### ISSUE THREAD

**Issue by kig1945** [Aha00a/AhaWiki#2]
![image](https://cloud.githubusercontent.com/assets/7609272/13245046/abe20062-da4d-11e5-9dca-0a873b611985.png)
- SimilarPages
  화면 하단에 링크 정보가 문제있습니다.
  스샷에 있는 오류 페이지 명은 "정보(Info)" 입니다.

**Comment by Aha00a** [comment]
A link information in "SimilarPages" is incorrect when the page name contains parenthesis.

**Comment by kig1945** [comment]
error page : http://wiki.kig1945.com/w/%EB%B0%9C%EC%9E%90%EC%B7%A8

정보(Info) page : http://wiki.kig1945.com/w/%EC%A0%95%EB%B3%B4%28Info%29
