### ISSUE TITLE
Style is broken in Windows edge.

### ISSUE THREAD

**Issue by kasanoppa** [Aha00a/AhaWiki#21]
See the capture.
Two problems you can see.
 1. Code block header broken. 
 1. Code block without text draw a blank.

![edge](https://user-images.githubusercontent.com/3467159/38774367-9e00be4a-40a1-11e8-9195-35659e569c17.png)
```
= test
describe test here.

[[[#!Vim sh
ls -al

]]]

 * 1
 * aaa
   *  [[[#!Vim sh
ls -al
]]]
   * ccc [[[#!Vim sh
ls -al
]]]
```

**Comment by Aha00a** [comment]
Help wanted. I don't have an `Edge` browser.

**Comment by Aha00a** [comment]
won't fix.
