### ISSUE TITLE
Code block somtimes didn't appear.

### ISSUE THREAD

**Issue by kasanoppa** [Aha00a/AhaWiki#22]
Some code block didn't appear.
So I was add a space at the end of line, the code block appeared.

![image](https://user-images.githubusercontent.com/3467159/38774392-5aefcc58-40a2-11e8-8d4d-e8b05f6df6aa.png)

Test syntax.
`= test
describe test here.

 * this ahs no space [[[#!Vim sh
npm i -g cordova@6.5.0
npm i -g ionic@2.2.1
]]]
 * this has space at last [[[#!Vim sh
npm i -g cordova@6.5.0
npm i -g ionic@2.2.1 
]]]
`

**Comment by Aha00a** [comment]
improved, but not solved completely.

**Comment by Aha00a** [comment]
solved.
