### ISSUE TITLE
Bad gateway http://ahawiki.aha00a.com of Readme.wiki

### ISSUE THREAD

**Issue by kasanoppa** [Aha00a/AhaWiki#4]
Readme.wiki
http://ahawiki.aha00a.com bad gateway

**Comment by kasanoppa** [comment]
It seems to be corrected to "http://wiki.aha00a.com/"

**Comment by Aha00a** [comment]
Thank you for reporting. 
I stopped service http://ahawiki.aha00a.com, because my server had overloaded. It will be back, soon. May the 4th be with you.
